import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { T1Service } from '../t-1.service';
import { IT1 } from '../it-1';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';


@Component({
  selector: 'app-t-1-new',
  templateUrl: './t-1-new.component.html',
  styleUrls: ['./t-1-new.component.scss']
})
export class T1NewComponent extends BaseNewComponent<IT1> implements OnInit {
  
    title:string = "New T1";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<T1NewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public t1Service: T1Service,
		public errorService: ErrorService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, t1Service, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'T1';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
    }
 		
	setForm(){
 		this.itemForm = this.formBuilder.group({
      	  ca: new FormArray([]),
      	  file:[],
      	  fileFileSource:[],
      	  flpa: new FormArray([]),
      	  fpa: new FormArray([]),
      id: ['', Validators.required],
      inet: [''],
      jb: [''],
      jbf: [''],
      str: [''],
    });
    
    this.fields = [
              {
      		  name: 'str',
      		  label: 'str',
      		  isRequired: false,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'jbf',
      		  label: 'jbf',
      		  isRequired: false,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'jb',
      		  label: 'jb',
      		  isRequired: false,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'inet',
      		  label: 'inet',
      		  isRequired: false,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'id',
      		  label: 'id',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.Number,
      	    },
              {
      		  name: 'fpa',
      		  label: 'fpa',
      		  isRequired: false,
      		  isAutoGenerated: false,
                type: FieldType.NumericArray,
      	    },
              {
      		  name: 'flpa',
      		  label: 'flpa',
      		  isRequired: false,
      		  isAutoGenerated: false,
                type: FieldType.NumericArray,
      	    },
              {
      		  name: 'file',
      		  label: 'file',
      		  isRequired: false,
      		  isAutoGenerated: false,
                type: FieldType.File,
      	    },
              {
      		  name: 'ca',
      		  label: 'ca',
      		  isRequired: false,
      		  isAutoGenerated: false,
                type: FieldType.Array,
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let t1 = this.itemForm.getRawValue();
             t1.file=t1.fileFileSource;
             delete t1.fileFileSource;
		super.onSubmit(t1);
		
	}
    
}
