import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { T3Service } from '../t-3.service';
import { IT3 } from '../it-3';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';


@Component({
  selector: 'app-t-3-new',
  templateUrl: './t-3-new.component.html',
  styleUrls: ['./t-3-new.component.scss']
})
export class T3NewComponent extends BaseNewComponent<IT3> implements OnInit {
  
    title:string = "New T3";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<T3NewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public t3Service: T3Service,
		public errorService: ErrorService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, t3Service, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'T3';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
    }
 		
	setForm(){
 		this.itemForm = this.formBuilder.group({
      	  score: new FormArray([]),
    });
    
    this.fields = [
              {
      		  name: 'score',
      		  label: 'score',
      		  isRequired: false,
      		  isAutoGenerated: false,
                   type : FieldType.Array,
                   subtype : FieldType.Number,
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let t3 = this.itemForm.getRawValue();
		super.onSubmit(t3);
		
	}
    
}
